site_name: My MK Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https:/github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: fontawesome/brands/linkedin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettejames/

copyright: Copyright &copy; 2023 James